In [3]:
import numpy as np

**Indexing with Arrays of Indices**

In [8]:
# the first 12 square numbers
a = np.arange(12)**2

# an array of indices
i = np.array([1,1,3,8,5])

# the elements of `a` at the positions
a[i]

# a bidimensional array of indices
j = np.array([[3,4], [9,7]])
# the same shape as `j`
a[j]

array([[ 9, 16],
       [81, 49]])

In [11]:
palette = np.array([[0,0,0],   # black
                    [255,0,0],    # red 
                    [0,255,0],    # green 
                    [0,0,255],    # blue 
                    [255,255,255]])   # white 
image = np.array([[0,1,2,0],
                  [0,3,4,0]])
palette[image]   # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [24]:
# we can also give indexes for more than one dimension.
# The arrays of indices for each dimension must have the same shape 
a = np.arange(12).reshape(3,4)
a

# indices for the first dim of `a`
i = np.array([[0,1], [1,2]])
# indices for the second dim
j = np.array([[2,1], [3,3]])

# i and j must have equal shape 
a[i,j]

a[i,2]

a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [27]:
# nd array using tuple
k = np.array(([2,3], (2,3)))
k

array([[2, 3],
       [2, 3]])

In [31]:
l = (i,j)

# equivalent to a[i,j]
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [38]:
# however, we cannot do this by putting i and j into an array,
# because this array will be interpreted as indexing the first 
# dimension of a.
s = np.array([i,j])

#not what we want 
# a[s]

# same as `a[i,j]`
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [53]:
# Another common use of indexing with arrays is the search
# of the maximum value of time-dependent series

# time scale 
time = np.linspace(20, 145, 5)

# time-dependent series
data = np.sin(np.arange(20).reshape(5,4))

data

# index of the maxima for each series 
ind = data.argmax(axis=0)
ind

# times corresponding to the maxima
time_max = time[ind]

data_max = data[ind, range(data.shape[1])]   # => [ind[0], 0], data[ind[1], 1]

time_max

data_max

np.all(data_max == data.max(axis=0))

True

In [57]:
# you can also use indexing with arrays as a target to assign to
a = np.arange(5)
a
a[[1,2,3,4]] = 0
a

array([0, 0, 0, 0, 0])

In [61]:
a = np.arange(5)
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

In [65]:
a = np.arange(5)
a[[0,0,2]] += 1
a

array([1, 1, 3, 3, 4])

**Indexing with Boolean Arrays**

In [69]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
# True all value greator than b
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
# 1D array with the selected elements
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [76]:
# all elements of `a` higher then 4 become 0
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [84]:
import matplotlib.pyplot as plt
def mandelbrot(h,w, maxit=20, r=2):
    """Returns an image of the mandelbrot fractal of size (h,w)"""
    x = np.linspace(-2.5, 1.5, 4*h+1)
    y = np.linspace(-1.5, 1.5, 3*w+1)
    A, B = np.meshgrid(x,y)
    C = A + B*1j
    z = np.zeros_like(C)
    divtime = maxit + np.zeros(z.shape, dtype=int)
    
    for i in range(maxit):
        z = z**2 + C
        diverge = abs(z) > r
        div_now = diverge & (divtime == maxit)
        divtime[div_now] = i
        z[diverge] = r
    return divtime 
mandelbrot(400,400)
# plt.imshow(mandelbrot(400,400))

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [85]:
a = np.arange(12).reshape(3,4)

# first dim selection
b1 = np.array([False, True, True])  

# Second dim selection
b2 = np.array([True, False, True, False])

# selecting rows 
a[b1, :]

# same thing
a[b1]

# selecting columns 
a[:, b2]

# a weird thing to do
a[b1, b2]

array([ 4, 10])

**The ix_() function**