In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x[2]

2

In [5]:
x[-2]

8

In [7]:
# now x is 2-dimensional
x.shape = (2,5)

In [8]:
x[1,3]

8

In [9]:
x[1,-1]

9

In [11]:
x[0]

array([0, 1, 2, 3, 4])

In [12]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [17]:
# start:stop:step
x[1:7:2]

array([1, 3, 5])

In [19]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [24]:
x = np.array([[[1],[2], [3]], [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [25]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [26]:
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# is equivalent to
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Each newaxis object in the selection tuple serves to expand the dimensions of the resulting 
# selection by one unit-length dimension.
# newaxis is an alias for None, and None can be used in place of this wth the same result.

x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [30]:
x[:, None, :, :].shape

(2, 1, 3, 1)

In [31]:
x = np.arange(5)
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [35]:
print("""Advanced indexing

Two types of advanced indexing:
    1. integer
    2. Boolean
    
Advanced indexing always returns a copy of the data.
""")

Advanced indexing

Two types of advanced indexing:
    1. integer
    2. Boolean



In [37]:
print("Integer array indexing")

Integer array indexing


In [40]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [41]:
x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [42]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [44]:
# if the index values are out of bounds then an IndexError is thrown
x = np.array([[1,2], [3,4], [5,6]])
x[np.array([1,-1])]


array([[3, 4],
       [5, 6]])

In [45]:
x[np.array([3,4])]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [48]:
# Advanced indices always are broadcase and iterated as one:
# if the indices cannot be broadcase  together with shapes... is raised
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [56]:
# first array tell the row index and second tell of element index position
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [51]:
y[np.array([0,2,4]), np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [52]:
# the boradcasting mechanism permit s index arrasy to be combined with scalars for other indices.
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

In [55]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [58]:
x = np.array([[1,2], [3,4], [5,6]])
x[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [62]:
x = np.array([[0,1,2],
             [3,4,5],
             [6,7,8],
             [9,10,11]])
rows = np.array([[0,0],[3,3]], dtype=np.intp)
columns = np.array([[0,2], [0,2]], dtype=np.intp)
x[rows,columns]

array([[ 0,  2],
       [ 9, 11]])

In [64]:
# since the indexing arrays above just repeat themselves, broadcasting
# can be used (compare operations such as rows[:, np.newaxis]+columns) to simplify this.
rows = np.array([0,3], dtype=np.intp)
columns = np.array([0,2], dtype=np.intp)
rows[:, np.newaxis]
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [66]:
# this broadcasting can also be achieved using the functino ix_:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [68]:
# NOTE: that with the np.ix_ call, only the diagonal elements would be selected:
x[rows, columns]

array([ 0, 11])

In [71]:
x = np.array([[1.,2.], [np.nan, 3.], [np.nan, np.nan]])

# select all entries from an array which are not NaN
x[~np.isnan(x)]

array([1., 2., 3.])

In [73]:
# or wish to add a constant to all non-negative element
x = np.array([1., -1., -2., 3])
x[x<0]+=20
x

array([ 1., 19., 18.,  3.])

In [76]:
x = np.arange(35).reshape(5,7)
b = x>20
b[:, 5]

array([False, False, False,  True,  True])

In [77]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [79]:
# from an array, select all rows which sum up to less or equal two
x = np.array([[0,1], [1,1], [2,2]])
rowsum = x.sum(-1)
x[rowsum<=2, :]

array([[0, 1],
       [1, 1]])

In [95]:
# Use boolean indexing to select all rows adding to an even number.
# At the same time columns 0 and 2 should be selected with an advanced integer index.
# using ix_() this can be done 
x = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11]
])
rows = (x.sum(-1)%2)==0
rows 
x.sum(-1)
columns = [0,2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [97]:
rows = rows.nonzero()[0]
x[rows[:, np.newaxis], columns]

array([[0, 2],
       [3, 5]])

In [100]:
# use ta 2-D boolean array of shape (2,3) with four True elements 
# to select rows from 3-D array of shape(2,3,5) result in a 2-D 
# result of shape (4,5)
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [104]:
b = np.array([[True, True, False], [False, True, True]])
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [105]:
"""Combining advanced and basic indexing"""

'Combining advanced and basic indexing'